### ISSUE TITLE
Second State - Getting started with Rust functions in Node.js

### ISSUE THREAD

**Issue by coding-to-music** [coding-to-music/coding-to-music.github.io#146]
https://www.secondstate.io/articles/getting-started-with-rust-function/

```
root@docker-ubuntu-s-1vcpu-2gb-nyc1-01:~/ap/wasmedge-nodejs-starter# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
info: downloading installer
warning: it looks like you have an existing installation of Rust at:
warning: /usr/bin
warning: rustup should not be installed alongside Rust. Please uninstall your existing Rust first.
warning: Otherwise you may have confusion unless you are careful with your PATH
warning: If you are sure that you want both rustup and your already installed Rust
warning: then please reply `y' or `yes' or set RUSTUP_INIT_SKIP_PATH_CHECK to yes
warning: or pass `-y' to ignore all ignorable checks.
error: cannot install while Rust is installed

Continue? (y/N) y


Welcome to Rust!

This will download and install the official compiler for the Rust
programming language, and its package manager, Cargo.

Rustup metadata and toolchains will be installed into the Rustup
home directory, located at:

  /root/.rustup

This can be modified with the RUSTUP_HOME environment variable.

The Cargo home directory located at:

  /root/.cargo

This can be modified with the CARGO_HOME environment variable.

The cargo, rustc, rustup and other commands will be added to
Cargo's bin directory, located at:

  /root/.cargo/bin

This path will then be added to your PATH environment variable by
modifying the profile files located at:

  /root/.profile
  /root/.bashrc

You can uninstall at any time with rustup self uninstall and
these changes will be reverted.

Current installation options:


   default host triple: x86_64-unknown-linux-gnu
     default toolchain: stable (default)
               profile: default
  modify PATH variable: yes

1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
>1

info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2021-06-17, rust version 1.53.0 (53cb7b09b 2021-06-17)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
 48.4 MiB /  48.4 MiB (100 %)  26.6 MiB/s in  1s ETA:  0s
info: downloading component 'rustfmt'
info: installing component 'cargo'
  6.0 MiB /   6.0 MiB (100 %)   5.3 MiB/s in  1s ETA:  0s
info: installing component 'clippy'
info: installing component 'rust-docs'
 16.1 MiB /  16.1 MiB (100 %)   1.7 MiB/s in  6s ETA:  0s
info: installing component 'rust-std'
 25.3 MiB /  25.3 MiB (100 %)   4.1 MiB/s in  6s ETA:  0s
info: installing component 'rustc'
 48.4 MiB /  48.4 MiB (100 %)   5.2 MiB/s in  9s ETA:  0s
info: installing component 'rustfmt'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu installed - rustc 1.53.0 (53cb7b09b 2021-06-17)


Rust is installed now. Great!

To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).

To configure your current shell, run:
source $HOME/.cargo/env
root@docker-ubuntu-s-1vcpu-2gb-nyc1-01:~/ap/wasmedge-nodejs-starter# sc
root@docker-ubuntu-s-1vcpu-2gb-nyc1-01:~/ap/wasmedge-nodejs-starter# source $HOME/.cargo/env
root@docker-ubuntu-s-1vcpu-2gb-nyc1-01:~/ap/wasmedge-nodejs-starter# rustup override set 1.50.0info: syncing channel updates for '1.50.0-x86_64-unknown-linux-gnu'
info: latest update on 2021-02-11, rust version 1.50.0 (cb75ad5db 2021-02-10)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
 60.3 MiB /  60.3 MiB (100 %)  30.4 MiB/s in  2s ETA:  0s
info: downloading component 'rustfmt'
info: installing component 'cargo'
  5.9 MiB /   5.9 MiB (100 %)   5.3 MiB/s in  1s ETA:  0s
info: installing component 'clippy'
info: installing component 'rust-docs'
 14.7 MiB /  14.7 MiB (100 %)   2.2 MiB/s in  6s ETA:  0s
info: installing component 'rust-std'
 24.5 MiB /  24.5 MiB (100 %)   4.3 MiB/s in  6s ETA:  0s
info: installing component 'rustc'
 60.3 MiB /  60.3 MiB (100 %)   5.3 MiB/s in 11s ETA:  0s
info: installing component 'rustfmt'
info: override toolchain for '/root/ap/wasmedge-nodejs-starter' set to '1.50.0-x86_64-unknown-linux-gnu'

  1.50.0-x86_64-unknown-linux-gnu installed - rustc 1.50.0 (cb75ad5db 2021-02-10)

root@docker-ubuntu-s-1vcpu-2gb-nyc1-01:~/ap/wasmedge-nodejs-starter# rust --version

Command 'rust' not found, did you mean:

  command 'trust' from deb p11-kit (0.23.20-1ubuntu0.1)
  command 'rst' from deb bro-aux (0.42-1)
  command 'rush' from deb rush (1.8+dfsg-1.1)
  command 'rustc' from deb rustc (1.47.0+dfsg1+llvm-1ubuntu1~20.04.1)

Try: apt install <deb name>

root@docker-ubuntu-s-1vcpu-2gb-nyc1-01:~/ap/wasmedge-nodejs-starter# curl -sL https://deb.nodesource.com/setup_14.x |  bash

## Installing the NodeSource Node.js 14.x repo...


## Populating apt-get cache...

+ apt-get update
Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:2 http://mirrors.digitalocean.com/ubuntu focal InRelease [265 kB]                                       
Hit:3 https://download.docker.com/linux/ubuntu focal InRelease                                              
Hit:4 https://repos.insights.digitalocean.com/apt/do-agent main InRelease                                   
Hit:5 https://cli.github.com/packages stable InRelease                                                      
Get:6 http://mirrors.digitalocean.com/ubuntu focal-updates InRelease [114 kB]
Get:7 http://mirrors.digitalocean.com/ubuntu focal-backports InRelease [101 kB]
Get:8 http://mirrors.digitalocean.com/ubuntu focal-updates/main amd64 Packages [1081 kB]
Get:9 http://mirrors.digitalocean.com/ubuntu focal-updates/main Translation-en [238 kB]
Get:10 http://mirrors.digitalocean.com/ubuntu focal-updates/main amd64 c-n-f Metadata [13.6 kB]
Get:11 http://mirrors.digitalocean.com/ubuntu focal-updates/universe amd64 Packages [827 kB]
Get:12 http://mirrors.digitalocean.com/ubuntu focal-updates/universe Translation-en [173 kB]
Get:13 http://mirrors.digitalocean.com/ubuntu focal-updates/universe amd64 c-n-f Metadata [17.8 kB]
Fetched 2943 kB in 3s (1119 kB/s) 
Reading package lists... Done

## Confirming "focal" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_14.x/dists/focal/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor | tee /usr/share/keyrings/nodesource.gpg >/dev/null

## Creating apt sources list file for the NodeSource Node.js 14.x repo...

+ echo 'deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_14.x focal main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_14.x focal main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Get:2 http://mirrors.digitalocean.com/ubuntu focal InRelease [265 kB]                                       
Hit:3 https://cli.github.com/packages stable InRelease                                                      
Hit:4 https://download.docker.com/linux/ubuntu focal InRelease                                              
Get:5 https://deb.nodesource.com/node_14.x focal InRelease [4583 B]                                         
Hit:6 https://repos.insights.digitalocean.com/apt/do-agent main InRelease                                   
Hit:7 http://mirrors.digitalocean.com/ubuntu focal-updates InRelease
Hit:8 http://mirrors.digitalocean.com/ubuntu focal-backports InRelease
Get:9 https://deb.nodesource.com/node_14.x focal/main amd64 Packages [768 B]
Fetched 270 kB in 2s (165 kB/s)
Reading package lists... Done

## Run `sudo apt-get install -y nodejs` to install Node.js 14.x and npm
## You may also need development tools to build native addons:
     sudo apt-get install gcc g++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null
     echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     sudo apt-get update && sudo apt-get install yarn


root@docker-ubuntu-s-1vcpu-2gb-nyc1-01:~/ap/wasmedge-nodejs-starter#      sudo apt-get install gcc g++ make
ll the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null
     echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
Reading package lists... Doneudo apt-get install yarn
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:9.3.0-1ubuntu2).
gcc set to manually installed.
The following packages were automatically installed and are no longer required:
  linux-headers-5.4.0-51 linux-headers-5.4.0-51-generic linux-image-5.4.0-51-generic
  linux-modules-5.4.0-51-generic
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  g++-9 libstdc++-9-dev
Suggested packages:
  g++-multilib g++-9-multilib gcc-9-doc libstdc++-9-doc make-doc
The following NEW packages will be installed:
  g++ g++-9 libstdc++-9-dev make
0 upgraded, 4 newly installed, 0 to remove and 3 not upgraded.
Need to get 10.3 MB of archives.
After this operation, 47.1 MB of additional disk space will be used.
Do you want to continue? [Y/n] Abort.
root@docker-ubuntu-s-1vcpu-2gb-nyc1-01:~/ap/wasmedge-nodejs-starter#      curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null
root@docker-ubuntu-s-1vcpu-2gb-nyc1-01:~/ap/wasmedge-nodejs-starter#      echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main
root@docker-ubuntu-s-1vcpu-2gb-nyc1-01:~/ap/wasmedge-nodejs-starter#      sudo apt-get update && sudo apt-get install yarn
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Get:2 http://mirrors.digitalocean.com/ubuntu focal InRelease [265 kB]                                       
Hit:3 http://mirrors.digitalocean.com/ubuntu focal-updates InRelease                                        
Hit:4 https://deb.nodesource.com/node_14.x focal InRelease                                                  
Hit:5 https://download.docker.com/linux/ubuntu focal InRelease                                              
Hit:6 https://repos.insights.digitalocean.com/apt/do-agent main InRelease                                   
Hit:7 https://cli.github.com/packages stable InRelease                                                      
Get:8 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]                              
Hit:9 http://mirrors.digitalocean.com/ubuntu focal-backports InRelease
Get:10 https://dl.yarnpkg.com/debian stable/main amd64 Packages [10.1 kB]
Get:11 https://dl.yarnpkg.com/debian stable/main all Packages [10.1 kB]
Fetched 302 kB in 2s (169 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-5.4.0-51 linux-headers-5.4.0-51-generic linux-image-5.4.0-51-generic
  linux-modules-5.4.0-51-generic
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  nodejs
The following NEW packages will be installed:
  nodejs yarn
0 upgraded, 2 newly installed, 0 to remove and 3 not upgraded.
Need to get 25.8 MB of archives.
After this operation, 126 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://dl.yarnpkg.com/debian stable/main amd64 yarn all 1.22.5-1 [891 kB]
Get:2 https://deb.nodesource.com/node_14.x focal/main amd64 nodejs amd64 14.17.1-deb-1nodesource1 [24.9 MB]
Fetched 25.8 MB in 1s (32.9 MB/s)                         
Selecting previously unselected package nodejs.
(Reading database ... 144499 files and directories currently installed.)
Preparing to unpack .../nodejs_14.17.1-deb-1nodesource1_amd64.deb ...
Unpacking nodejs (14.17.1-deb-1nodesource1) ...
Selecting previously unselected package yarn.
Preparing to unpack .../archives/yarn_1.22.5-1_all.deb ...
Unpacking yarn (1.22.5-1) ...
Setting up nodejs (14.17.1-deb-1nodesource1) ...
Setting up yarn (1.22.5-1) ...
Processing triggers for man-db (2.9.1-1) ...
root@docker-ubuntu-s-1vcpu-2gb-nyc1-01:~/ap/wasmedge-nodejs-starter# nodejs --version

Command 'nodejs' not found, but can be installed with:

apt install nodejs

root@docker-ubuntu-s-1vcpu-2gb-nyc1-01:~/ap/wasmedge-nodejs-starter# node --version
v14.17.1
root@docker-ubuntu-s-1vcpu-2gb-nyc1-01:~/ap/wasmedge-nodejs-starter# yarn --version
1.22.5
root@docker-ubuntu-s-1vcpu-2gb-nyc1-01:~/ap/wasmedge-nodejs-starter# sudo apt-get install -y nodejs npm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nodejs is already the newest version (14.17.1-deb-1nodesource1).
nodejs set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nodejs : Conflicts: npm
 npm : Depends: node-gyp (>= 3.6.2~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
root@docker-ubuntu-s-1vcpu-2gb-nyc1-01:~/ap/wasmedge-nodejs-starter# apt install node-gyp
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 node-gyp : Depends: libnode-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
root@docker-ubuntu-s-1vcpu-2gb-nyc1-01:~/ap/wasmedge-nodejs-starter# sudo apt update
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Get:2 http://mirrors.digitalocean.com/ubuntu focal InRelease [265 kB]                                       
Hit:3 http://mirrors.digitalocean.com/ubuntu focal-updates InRelease                                        
Hit:4 http://mirrors.digitalocean.com/ubuntu focal-backports InRelease                                      
Hit:5 https://download.docker.com/linux/ubuntu focal InRelease                                              
Hit:6 https://deb.nodesource.com/node_14.x focal InRelease                                                  
Hit:7 https://cli.github.com/packages stable InRelease                                                      
Hit:8 https://dl.yarnpkg.com/debian stable InRelease                
Hit:9 https://repos.insights.digitalocean.com/apt/do-agent main InRelease
Fetched 265 kB in 2s (156 kB/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
3 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@docker-ubuntu-s-1vcpu-2gb-nyc1-01:~/ap/wasmedge-nodejs-starter# sudo apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  linux-headers-5.4.0-51 linux-headers-5.4.0-51-generic linux-image-5.4.0-51-generic
  linux-modules-5.4.0-51-generic
Use 'sudo apt autoremove' to remove them.
The following packages will be upgraded:
  gh linux-base linux-firmware
3 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 111 MB of archives.
After this operation, 1533 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://mirrors.digitalocean.com/ubuntu focal-updates/main amd64 linux-base all 4.5ubuntu3.5 [17.8 kB]
Get:2 http://mirrors.digitalocean.com/ubuntu focal-updates/main amd64 linux-firmware all 1.187.15 [104 MB]
Get:3 https://cli.github.com/packages stable/main amd64 gh amd64 1.12.0 [6932 kB]
Fetched 111 MB in 3s (39.1 MB/s)                             
Preconfiguring packages ...
(Reading database ... 149438 files and directories currently installed.)
Preparing to unpack .../linux-base_4.5ubuntu3.5_all.deb ...
Unpacking linux-base (4.5ubuntu3.5) over (4.5ubuntu3.1) ...
Preparing to unpack .../linux-firmware_1.187.15_all.deb ...
Unpacking linux-firmware (1.187.15) over (1.187.14) ...
Preparing to unpack .../archives/gh_1.12.0_amd64.deb ...
Unpacking gh (1.12.0) over (1.11.0) ...
Setting up linux-base (4.5ubuntu3.5) ...
Setting up linux-firmware (1.187.15) ...
update-initramfs: Generating /boot/initrd.img-5.4.0-77-generic
update-initramfs: Generating /boot/initrd.img-5.4.0-52-generic
update-initramfs: Generating /boot/initrd.img-5.4.0-51-generic
Setting up gh (1.12.0) ...
Processing triggers for man-db (2.9.1-1) ...
root@docker-ubuntu-s-1vcpu-2gb-nyc1-01:~/ap/wasmedge-nodejs-starter# npm --version
6.14.13
root@docker-ubuntu-s-1vcpu-2gb-nyc1-01:~/ap/wasmedge-nodejs-starter# node --version
v14.17.1
root@docker-ubuntu-s-1vcpu-2gb-nyc1-01:~/ap/wasmedge-nodejs-starter# npm install -g rustwasmc # Append --unsafe-perm if permission denied
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
/usr/bin/rustwasmc -> /usr/lib/node_modules/rustwasmc/run.js

> rustwasmc@0.1.28 postinstall /usr/lib/node_modules/rustwasmc
> node ./install.js

/usr/lib/node_modules/rustwasmc/node_modules/mkdirp/index.js:91
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/root/.config/rustwasmc-nodejs'
    at Object.mkdirSync (fs.js:1009:3)
    at Function.sync (/usr/lib/node_modules/rustwasmc/node_modules/mkdirp/index.js:72:13)
    at Binary._getInstallDirectory (/usr/lib/node_modules/rustwasmc/node_modules/binary-install/src/binary.js:49:14)
    at Binary.install (/usr/lib/node_modules/rustwasmc/node_modules/binary-install/src/binary.js:75:22)
    at install (/usr/lib/node_modules/rustwasmc/binary.js:41:10)
    at Object.<anonymous> (/usr/lib/node_modules/rustwasmc/install.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/root/.config/rustwasmc-nodejs'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rustwasmc@0.1.28 postinstall: `node ./install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rustwasmc@0.1.28 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-30T05_45_19_959Z-debug.log
root@docker-ubuntu-s-1vcpu-2gb-nyc1-01:~/ap/wasmedge-nodejs-starter# npm install axios
npm WARN saveError ENOENT: no such file or directory, open '/root/ap/wasmedge-nodejs-starter/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/root/ap/wasmedge-nodejs-starter/package.json'
npm WARN wasmedge-nodejs-starter No description
npm WARN wasmedge-nodejs-starter No repository field.
npm WARN wasmedge-nodejs-starter No README data
npm WARN wasmedge-nodejs-starter No license field.

+ axios@0.21.1
added 2 packages from 4 contributors and audited 2 packages in 0.91s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

root@docker-ubuntu-s-1vcpu-2gb-nyc1-01:~/ap/wasmedge-nodejs-starter# npm install -g rustwasmc # Append --unsafe-perm if permission denied
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
/usr/bin/rustwasmc -> /usr/lib/node_modules/rustwasmc/run.js

> rustwasmc@0.1.28 postinstall /usr/lib/node_modules/rustwasmc
> node ./install.js

/usr/lib/node_modules/rustwasmc/node_modules/mkdirp/index.js:91
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/root/.config/rustwasmc-nodejs'
    at Object.mkdirSync (fs.js:1009:3)
    at Function.sync (/usr/lib/node_modules/rustwasmc/node_modules/mkdirp/index.js:72:13)
    at Binary._getInstallDirectory (/usr/lib/node_modules/rustwasmc/node_modules/binary-install/src/binary.js:49:14)
    at Binary.install (/usr/lib/node_modules/rustwasmc/node_modules/binary-install/src/binary.js:75:22)
    at install (/usr/lib/node_modules/rustwasmc/binary.js:41:10)
    at Object.<anonymous> (/usr/lib/node_modules/rustwasmc/install.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/root/.config/rustwasmc-nodejs'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rustwasmc@0.1.28 postinstall: `node ./install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rustwasmc@0.1.28 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-30T05_47_16_938Z-debug.log
root@docker-ubuntu-s-1vcpu-2gb-nyc1-01:~/ap/wasmedge-nodejs-starter# 
```

**Comment by coding-to-music** [comment]
# Prerequisites
To set up a high-performance Node.js environment with Rust and WebAssembly, you will need the following:

- A modern Linux distribution, such as Ubuntu Server 20.04 TLS
Rust language
- Node.js
- (The WasmEdge Runtime)[https://github.com/WasmEdge/WasmEdge]
- The rustwasmc compiler toolchain

**Comment by coding-to-music** [comment]
# Set up Rust & WebAssembly in Node.js
https://www.secondstate.io/articles/setup-rust-nodejs/

## Manual setup
Of course, not everyone wants to use Docker. In the rest of the article, we will walk through setps for a manual setup in a fresh Ubuntu Server 20.04 distribution. The whole system takes 10 minutes to set up. We will install Rust, Node.js, the WasmEdge Runtime, and the rustwasmc compiler tool.

## Setup the Operating System
We recommend you use the Ubuntu 20.04 LTS or later. WasmEdge depends on the latest version of the libstdc++ library, which is already installed on Ubuntu 20.04. If you are using another Linux distribution, please make sure that GLIBCXX >= 3.4.28 or upgrade as needed.

Then, use the commands below to bring your operating system up to date with the latest developer tools.

```python
sudo apt-get update
sudo apt-get -y upgrade
sudo apt install -y build-essential libboost-all-dev llvm-dev liblld-10-dev
sudo apt install -y curl wget git vim pkg-config libssl-dev // Optional dev tools
```
### If you are using the Tensorflow WASI API for AI-as-a-Service applications, install the Tensorflow library and its dependencies too.

```python
sudo apt install -y libjpeg-dev libpng-dev


wget https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.3.0.tar.gz
sudo tar -C /usr/local -xzf libtensorflow-cpu-linux-x86_64-2.3.0.tar.gz

wget https://github.com/second-state/ssvm-tensorflow-deps/releases/download/0.1.0/ssvm-tensorflow-deps-lite-0.1.0-linux-x64.tar.gz
tar -zxvf ssvm-tensorflow-deps-lite-0.1.0-linux-x64.tar.gz
sudo cp ./libtensorflowlite_c.so /usr/local/lib

sudo ldconfig
```

# Rust
Installing Rust on your Linux machine is very easy. Just two commands. At this time, we only supports up to Rust 1.50.0.

```python
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
source $HOME/.cargo/env
rustup override set 1.50.0
```
For more options on installing Rust on different systems, please refer to the official Rust documentation.

# Node.js
The best way to install Node.js on Linux is through the NVM tool. NVM allows you to use the latest Node.js, and change easily when you need to test your code on a different version of Node.js.

```python
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
export NVM_DIR="$HOME/.nvm"
$ [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
$ [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

nvm install v12.18.3
nvm use v12.18.3
```
For more options on installing Node.js on different systems, please refer to the official Node.js documentation.

# WasmEdge Runtime
The WasmEdge Runtime is an open source WebAssembly runtime optimized for edge cloud and device applications. Use the following commands to install it as a Node.js module.

```python
npm install wasmedge
If you are using the Tensorflow WASI API for AI-as-a-Service applications, install WasmEdge with extensions.

npm install wasmedge-extensions
```

The rustwasmc compiler toolchain
The rustwasmc tool provides an easy command to compile Rust functions into WebAssembly and it automatically generates Node.js and WasmEdge integration code. Since you already have Node.js installed, this just requires one command.

```python
$ npm install -g rustwasmc # Append --unsafe-perm if permission denied
```

What’s next?
Now you have all the tools, get started with a hello world example!

**Comment by coding-to-music** [comment]
# The rustwasmc compiler toolchain
The rustwasmc tool provides an easy command to compile Rust functions into WebAssembly and it automatically generates Node.js and WasmEdge integration code. Since you already have Node.js installed, this just requires one command.

```python
root@docker-ubuntu-s-1vcpu-2gb-nyc1-01:~/ap/wasmedge-nodejs-starter# npm install -g rustwasmc # Append --unsafe-perm if permission denied
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
/usr/bin/rustwasmc -> /usr/lib/node_modules/rustwasmc/run.js

> rustwasmc@0.1.28 postinstall /usr/lib/node_modules/rustwasmc
> node ./install.js

/usr/lib/node_modules/rustwasmc/node_modules/mkdirp/index.js:91
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/root/.config/rustwasmc-nodejs'
    at Object.mkdirSync (fs.js:1009:3)
    at Function.sync (/usr/lib/node_modules/rustwasmc/node_modules/mkdirp/index.js:72:13)
    at Binary._getInstallDirectory (/usr/lib/node_modules/rustwasmc/node_modules/binary-install/src/binary.js:49:14)
    at Binary.install (/usr/lib/node_modules/rustwasmc/node_modules/binary-install/src/binary.js:75:22)
    at install (/usr/lib/node_modules/rustwasmc/binary.js:41:10)
    at Object.<anonymous> (/usr/lib/node_modules/rustwasmc/install.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/root/.config/rustwasmc-nodejs'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rustwasmc@0.1.28 postinstall: `node ./install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rustwasmc@0.1.28 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-01T22_54_33_328Z-debug.log
```
